
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mogqmymxnienxqactuym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vZ3FteW14bmllbnhxYWN0dXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzEwNTgsImV4cCI6MjA1ODEwNzA1OH0.Z2bzbA8aQQha2NhgA0M1F2R56Ewv8npqRgCj2S_70h4";

// Create a single, persistent Supabase client instance
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Prevent auto-refreshing on navigation
  },
  realtime: {
    params: {
      eventsPerSecond: 1, // Limit realtime events to reduce load
    },
  },
  global: {
    fetch: (...args) => {
      const fetchFn = fetch;
      // Add timeout to prevent hanging requests
      return Promise.race([
        fetchFn(...args),
        new Promise((_, reject) => 
          setTimeout(() => reject(new Error('Supabase request timeout')), 10000)
        ),
      ]) as Promise<Response>;
    },
  },
});
